name: TFApply

on: [push]

jobs:
  tfapply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ams0/terraform-apply-for-azure-action@v4
      with:
        arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
        arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        path: ../vm
